on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_CICD_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_CICD_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_CICD_PASSWORD: ${{ secrets.SNOWFLAKE_PAT }}
      SNOWFLAKE_CONNECTIONS_CICD_AUTHENTICATOR: programmatic_access_token
    steps:
      - uses: actions/checkout@v4
      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
      - name: Test connection
        run: snow connection test --connection cicd -x
      - name: Run SQL
        run: snow sql -q "SELECT CURRENT_USER(), CURRENT_ROLE(), '${{ inputs.environment }}' AS ENVIRONMENT" -x